base_url = "https://schof.co"
title = "Thomas Schoffelen"

taxonomies = [{ name = "category", feed = true, render = true }]

compile_sass = true

generate_feeds = true
feed_filenames = ["rss.xml"]
feed_limit = 50
default_language = "en"
author = "Thomas Schoffelen"

[markdown]
highlight_code = true
highlight_theme = "two-dark"
